#ifndef __BMS_PROTECTION_H
#define __BMS_PROTECTION_H

#define CELL_VOLTAGE_MAX 4200 // mV
#define CELL_VOLTAGE_MIN 3000 // mV
#define CELL_VOLTAGE_WARNING 2700 // mV
#define CELL_VOLTAGE_CRITICAL 2300 // mV

#define DISCHARGE_CURRENT_MAX 110 // A
#define CHARGE_CURRENT_MAX -20 // A
#define CHARGE_CURRENT_THRESHOLD -1 // A

#define IC_TEMPERATURE_MAX 65.0f // °C
#define IC_TEMPERATURE_HIGH_THRESHOLD 60.0f // °C
#define BATTERY_TEMPERATURE_MAX 55.0f // °C
#define BATTERY_TEMPERATURE_HIGH_THRESHOLD 50.0f // °C
#define BATTERY_TEMPERATURE_MIN -20.0f // °C
#define BATTERY_TEMPERATURE_LOW_THRESHOLD -15.0f // °C
#define BATTERY_TEMPERATURE_MIN_CHARGE 0 // °C
#define BATTERY_TEMPERATURE_LOW_THRESHOLD_CHARGE 5.0f // °C

void BMS_Protection_Task(void);

#endif
