name: Build LCM

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'  # This assumes that your version tags are prefixed with 'v'

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build_release:
    needs: create_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cell_type: [P42A, DG40]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCC
        uses: actions/setup-python@v2
        with:
          gcc-version: '11'  # Specify the GCC version you need

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential gcc-arm-none-eabi

      - name: Build project
        run: |
          cd LCM
          make CELL_TYPE=${{ matrix.cell_type }}

      - name: Release app.hex
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./LCM/Build/app.hex
          asset_name: lcm-${{ matrix.cell_type }}.hex
          asset_content_type: application/octet-stream

  build_artifact:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cell_type: [P42A, DG40]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCC
        uses: actions/setup-python@v2
        with:
          gcc-version: '11'  # Specify the GCC version you need

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential gcc-arm-none-eabi

      - name: Build project
        run: |
          cd LCM
          make CELL_TYPE=${{ matrix.cell_type }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lcm-${{ matrix.cell_type }}.hex
          path: ./LCM/Build/app.hex
